services:
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: $DATABASE_URL
    depends_on:
      - db
    networks:
      - airbnb-uta

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    networks:
      - airbnb-uta

  db:
    image: postgres:16
    ports:
      - 6789:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - airbnb-uta

volumes:
  db-data:
networks:
  airbnb-uta:
