services:
  db-dev:
    image: postgres:16
    ports:
      - 6789:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - airbnb-uta
    env_file:
      - .env
    volumes:
      - db-dev-vol:/var/lib/postgresql/data

  db-test:
    image: postgres:16
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - airbnb-uta
    env_file:
      - .env
    volumes:
      - db-test-vol:/var/lib/postgresql/data

volumes:
  db-dev-vol:
  db-test-vol:
networks:
  airbnb-uta:
