services:
  db-dev:
    image: postgres
    ports: 
      - 6789:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - airbnb-uta
networks:
  airbnb-uta:
