version: '3.9'
services:
  db-dev:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - airbnb-uta
networks: 
  airbnb-uta: