# Usar node:18 para el contenedor
FROM node:18-alpine

# Establecer un directorio de trabajo propio dentro del contenedor
WORKDIR /app/backend

# Copiar el archivo de las dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar los archivos de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build

# Exponer el puerto de la aplicación
EXPOSE 3000

# Ejecutar las migraciones de Prisma y luego iniciar la aplicación
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]